version: "3.9"

services:
  dash-app:
    image: ghcr.io/ozeliurs/polyminorviz/dash-app:latest
    container_name: "dash-app"
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dash-app.rule=Host(`dash.ozeliurs.com`)"
      - "traefik.http.routers.dash-app.entrypoints=websecure"
      - "traefik.http.routers.dash-app.tls=true"
      - "traefik.http.routers.dash-app.tls.certresolver=cloudflare"
      - "traefik.http.services.dash-app.loadbalancer.server.port=8050"

networks:
  traefik:
    external: true